import { RouteInfo } from "./cabecera.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Personal",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: "mdi mdi-gauge",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "UI Components",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [], 
  },
  {
    path: "/usuario",
    title: "usuario",
    icon: "mdi mdi-blur-radial",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/cliente",
    title: "cliente",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/articulos",
    title: "articulos",
    icon: "mdi mdi-message-bulleted",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/albaranes",
    title: "albaranes",
    icon: "mdi mdi-view-carousel",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/facturas",
    title: "facturas",
    icon: "mdi mdi-arrange-bring-to-front",
    class: "",
    extralink: false,
    submenu: [],
  },
];
