import { RouteInfo } from "./cabecera.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "modulos",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  },
  {
    path: "/usuario",
    title: "USUARIOS",
    icon: "mdi mdi-blur-radial",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/cliente",
    title: "CLIENTES",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/articulos",
    title: "ARTICULOS",
    icon: "mdi mdi-message-bulleted",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/alta-pedido",
    title: "NUEVO PEDIDO",
    icon: "mdi mdi-message-bulleted",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/albaranes",
    title: "ALBARANES",
    icon: "mdi mdi-view-carousel",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/facturas",
    title: "FACTURAS",
    icon: "mdi mdi-arrange-bring-to-front",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "",
    title: "información",
    icon: "mdi mdi-dots-horizontal",
    class: "nav-small-cap",
    extralink: true,
    submenu: [],
  }, 
  {
    path: "/datos",
    title: "DATOS EMPRESA ",
    icon: "mdi mdi-arrange-bring-to-front",
    class: "",
    extralink: false,
    submenu: [],
  },
];
